"""Author the dataset-specific bank. These are candidate tests, not computed findings."""
import json
from pathlib import Path
rows=[
('rate-vs-volume','Sales','Realized-rate changes account for more of Summit Field’s matched-period sales movement than sold-unit volume.','Run the exact SKU × channel Shapley bridge and compare absolute rate, volume and mix contributions.','The rate contribution is smaller than volume or reverses the headline direction.','pvm',['fact_sales_line','fact_transaction','dim_date'],'All business; current versus comparison dates.','Sales before returns; integer-cent reconciled bridge.','The generator adds $3 to regular prices in 2025, but discounts and mix also affect realized rate. This is not price elasticity.'),
('q4-markdown','Pricing','Summit Field’s October–December markdown share is higher than its other observed months.','Aggregate markdown / effective regular merchandise sales by calendar month; compare Q4 only when both Q4 and other months are in scope.','Observed Q4 markdown share is not higher, or the selected dates lack a valid comparison.','q4-markdown',['fact_sales_line','fact_transaction','dim_date'],'Selected sale dates, monthly, all divisions and channels.','Markdown cents / gross sales cents.','Q4 10% unit markdown is a documented construction rule; rounding and product weighting affect the observed ratio.'),
('app-price-book','Pricing','The App price book is lower than Web and POS for the same SKU/quarter universe in the selected interval.','Compare overlapping price intervals across all channels; the generated assortment covers the same SKU/quarter cells. Inspect counts before comparing.','The price-book averages are equal/higher for App or the SKU/quarter universes differ.','app-price-book',['fact_price_history','dim_channel'],'Price intervals overlapping the selected dates; unweighted price-book comparison.','Effective regular price per SKU/channel/quarter, before markdown or promotion.','The generator sets App $1 below other channels. This tests the price book, not the observed basket ASP or customer response.'),
('digital-softgoods-returns','Returns','Web and App Apparel/Footwear sales have higher observed unit return rates than Store POS in the same sale cohorts.','Compare returned units / original sold units separately for Apparel and Footwear by channel.','Digital unit return rates are no higher than POS or a base is too small to compare.','digital-softgoods-returns',['fact_sales_line','fact_return_line','fact_transaction','dim_channel'],'Apparel and Footwear; selected original sale dates; all linked returns.','Unit return rate on fully observed 60-day sales cohorts.','The generator uses 17% digital versus 9% POS line return probability. One returned unit per selected line means unit return rates need not equal those probabilities.'),
('damaged-recovery','Margin','Damaged returns reduce merchandise margin more per returned unit because they recover no product cost.','Compare recovered_cost_cents by return reason on selected original sales cohorts; inspect actual reason labels.','Damaged return rows recover cost, or no damaged returns are observed in scope.','damaged-recovery',['fact_return_line','fact_sales_line','dim_return_reason','dim_date'],'Returns linked to selected original sales; all observed return dates.','Refunded merchandise and recovered cost, positive stored cents.','Non-damaged returns are restockable by construction. This excludes processing, shipping and labor costs.'),
('margin-refunds','Margin','Returned merchandise and recovered COGS explain a material difference between original sales growth and cohort merchandise-margin growth.','Reconcile original net sales − refunds − original COGS + recovered COGS in both periods.','Return-related component deltas are immaterial and the gap is explained by other accounting components.','margin',['fact_sales_line','fact_return_line'],'All divisions; matched original sale cohorts.','Cohort merchandise margin after all observed returns.','Accounting attribution does not identify causes of returns or measure operating profit.'),
('anonymous-orders','Customers','Pooling customer_key 0 as a real buyer would distort Summit Field’s repeat and customer-reach analysis.','Measure anonymous versus identified orders and sales; confirm distinct identified buyers exclude 0.','No anonymous orders are present in scope.','anonymous-orders',['fact_transaction','dim_date'],'Completed orders in selected dates.','Order/sales coverage by identity; anonymous key 0 excluded from buyer counts.','The generator targets 28% anonymous orders. It is not legitimate to infer anonymous-customer loyalty or repeat behavior.'),
('loyalty-attachment','Loyalty','Loyalty-attached orders have different observed AOV and unit baskets from unattached orders.','Compare header-based sales / orders and units / orders for loyalty_key > 0 versus 0.','Differences in basket measures are immaterial under a stated business threshold.','loyalty',['fact_transaction','dim_date'],'Selected completed orders; loyalty attached versus not attached.','AOV before returns; no header-to-line fan-out.','Enrollment and attachment are synthetic selection rules. Differences do not measure the loyalty program’s impact.'),
('mature-repeat','Customers','The newest first-observed purchase cohorts appear weaker if incomplete 90/180-day windows are treated as non-repeat.','Inspect eligible_90 / eligible_180 and compare repeat only among customers with mature observation windows.','All compared cohorts are fully mature and the proposed maturity artifact cannot explain the difference.','cohorts',['fact_transaction','dim_date'],'Identified buyers; first observed purchase in selected dates; history through selected end.','Repeat on a later date within 90/180 days; mature eligible denominator.','History is left-censored at 2024-01-01. First observed is not proven acquisition, and same-day repeat orders are excluded by the existing recipe.'),
('seasonal-divisions','Merchandise','Outdoor unit share rises in June/July, Footwear in August/September, and Apparel in November–January within the observed calendar.','Compare monthly division-unit shares, using all-division monthly units as the denominator; inspect both years when available.','The expected division-share pattern is absent or dates do not cover the relevant and adjacent months.','seasonal-divisions',['fact_sales_line','fact_transaction','dim_date'],'Selected sale dates; monthly division groups.','Original sold units and sales before returns.','These are explicit seasonal preferences in the generator, not newly discovered real-world consumer preferences.'),
('private-label-mix','Merchandise','The private-label group has different cohort margin and unit-return rates from other brands.','Classify using v_product.is_private_label; calculate margin / cohort realized sales and returned / original units.','Differences are negligible or attributable entirely to division/product composition in follow-up tests.','private-label-mix',['fact_sales_line','fact_return_line','dim_brand','dim_style','dim_sku'],'Selected sale cohorts, all channels, private-label flag rather than a guessed brand name.','Cohort realized revenue, merchandise margin, original and returned units.','Brand assignment is synthetic. Group comparisons mix product composition and do not measure brand preference.'),
('campaign-eligibility','Promotions','Loyalty-only and channel-restricted campaigns produce different redeemed sales and discount exposure across POS, Web and App.','Measure redeemed lines, units, net sales and promotion discount by loyalty_only and actual order channel.','No material exposure difference is present, or the scope lacks both campaign types.','promotion-eligibility',['dim_promotion','fact_sales_line','fact_transaction','dim_channel'],'Redeemed sale lines with promotion_key > 0 in selected dates.','Promotion-associated merchandise sales before returns.','Campaign eligibility, timing on days 10–24, and 60% eligible redemption are generator rules. No randomized holdout supports causal lift.'),
('pos-digital-baskets','Channels','POS, Web and App contribute differently to the sales movement because order counts and average baskets move differently.','Compare matched header-based order totals, units and AOV by channel; reconcile sales to the overall headline.','Channel contributions and within-channel basket changes do not explain the measured movement.','channels',['fact_transaction','dim_channel','dim_store','dim_date'],'Matched sale periods; digital selling_store_key 0 kept separate from POS stores.','Header net merchandise sales and AOV before returns.','The generator targets 66% POS, 23% Web, 11% App. Differences do not measure channel effectiveness.'),
('weekend-demand-weight','Calendar','Completed orders per observed day are higher on weekends than weekdays in Summit Field.','Compare order count divided by observed calendar-day count, split by dim_date.is_weekend.','Weekend orders per observed day are no higher, or holiday/month composition explains the difference in a follow-up.','weekend-concentration',['fact_transaction','dim_date'],'Selected sale dates; weekend versus weekday.','Completed orders per day; not foot traffic or conversion.','The generator adds weekend sampling weight; control month composition for a like-for-like comparison.'),
('fulfillment-baskets','Fulfillment','Pickup, DC shipping and ship-from-store orders have different basket sizes and observed return rates.','Inspect order totals, original sales, sold units and linked returned units by fulfillment method; distinguish carry-out.','Observed differences are immaterial or disappear within channel/division strata.','fulfillment',['fact_transaction','fact_sales_line','fact_return_line','dim_fulfillment_method'],'Selected completed sale cohorts; all observed returns.','Original sales / orders for AOV; cohort returned units / original units.','Only promise dates exist. This cannot test on-time delivery, delivery cost or causal retention effects.'),
('inventory-buffer','Inventory','Some divisions carry more available inventory relative to observed SKU sales rates, despite all generated locations stocking every SKU.','Compare latest completed available balances with selected-period units per week; inspect zero-sale SKUs separately.','Comparable weeks-of-supply differences are small or high stock is proportional to observed sales.','velocity',['fact_inventory_weekly','fact_sales_line','dim_sku'],'SKU totals over all locations; latest completed snapshot on/before selected end.','Available units / observed sales units per week; not a sum of weekly inventory balances.','Receipts are generated to cover sales. The model has no daily stockout, unmet-demand or actual replenishment lead-time process.'),
('inventory-reconciliation','Inventory','The latest inventory balance is explained by opening stock, receipts, sold units, restockable returns and shrink.','Verify opening + receipts + restocks − sold − shrink = closing at the latest completed snapshot.','A nonzero reconciliation residual appears; investigate data or aggregation errors before interpreting performance.','inventory',['fact_inventory_weekly','dim_sku'],'One latest completed Monday–Sunday snapshot; division totals.','Stock/flow reconciliation in units; available = closing − reserved.','This is a data-integrity hypothesis. Passing does not prove optimized stocking or absence of intraday stockouts.'),
('division-contribution','Sales','One of Apparel, Footwear, Team Sports, Outdoor, Golf or Fitness accounts for a disproportionate share of the matched-period sales change.','Rank division dollar contributions by absolute size and reconcile their sum to the header-based total change.','Contributions are broadly distributed and no division is material under a declared threshold.','growth',['fact_sales_line','fact_transaction','dim_date'],'Six merchandise divisions, matched dates, all channels.','Original merchandise sales before returns, current minus comparison.','Divisions locate where change occurred. They are not independent causes and should not be added to overlapping channel/brand decompositions.')
]
items=[]
for r in rows:
 ident,domain,hyp,test,fals,recipe,tables,scope,basis,limit=r
 items.append(dict(id=ident,domain=domain,hypothesis=hyp,test=test,falsifier=fals,test_recipe=recipe,required_tables=tables,evidence=', '.join(tables),scope=scope,metric_basis=basis,limitation=limit,playbooks=[recipe],status='untested_template',provenance='Summit Field METRICS.md, MODEL.md, executable playbooks and verified catalog; Milky Way deck is a workflow reference only.'))
Path(__file__).with_name('hypotheses.json').write_text(json.dumps(items,indent=2)+'\n')
